version: '3.9'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: file_service_db
      MYSQL_ROOT_PASSWORD: bismillah
    restart: always
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SHOW databases'"
      interval: 10s
      retries: 3
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"